<?php
/**
 * Created by PhpStorm.
 * User: harry
 * Date: 5/15/18
 * Time: 7:54 AM
 */

namespace Sample\Tests\unit;

use PHPUnit\Framework\TestCase;

class Base extends TestCase
{
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        \Mockery::close();
    }
}